all: compile-server

compile-server:
	javac Server/Common/*.java Server/Interface/*.java Server/ResourceManagers/*.java Middleware/*.java

clean:
	rm -f Server/Common/*.class Server/Interface/*.class Server/ResourceManagers/*.class Middleware/*.class